# Generated by Django 4.2.3 on 2023-07-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('callsign', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('base_airport', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer_serial_number', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('number_of_engines', models.IntegerField()),
                ('operator_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_control.airline')),
            ],
        ),
    ]
