# Generated by Django 4.2.3 on 2023-07-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_control', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
